@startuml
skin rose
'skinparam actorStyle awesome|Hollow

'default direction
' top to bottom direction
left to right direction

actor "终端用户" as User << Human >> #pink;line:darkred;line.bold;text:red

rectangle 登陆逻辑 {
    actor "后台管理员" as Admin

    usecase "登陆" as Login #orange;line:red;line.bold;text:red
    note bottom: 注意安全方式
    usecase "查询密码" as Query
    note top : RPC调用

    usecase "获取个人信息" as GetInfo
    usecase "操作数据库" as Database
    GetInfo ..> Database #blue;line.dashed;text:blue : <<include>>
    usecase "读写内存" as CacheMemery
    GetInfo ..> CacheMemery : <<include>>
}

User --> Login : 使用浏览器
User --> Query : 校验
User --> GetInfo #green;text:green : 显示

Admin -u-> Login
@enduml