@startuml
'https://plantuml.com/use-case-diagram
skin rose

title
    <b><font size=17>整体类图</font></b>
end title

interface ios_base




abstract AbstractCollection
interface List
abstract class AbstractList
class ArrayList {
    Object[] elementData
    size()
}

enum TimeUnit {
    DAYS
    HOURS
    MINUTES
}

Collection <|-- AbstractCollection
Collection <|-- List
List <|-- AbstractList

AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList


@enduml