@startuml
skin rose
skinparam packageStyle rectangle

title
    <b><font size=17>整体IO库类图</font></b>
end title

package ios #whiteSmoke {
    enum iostate
    enum fmtflags
    class ios_base <<typename _CharT,typename _Traits>> {
        # ios_base() throw ();
        + virtual ~ios_base();
        ==members==
        # iostate _M_exception;
    }
    note top of ios_base : 所有父类

    class basic_ios extends ios_base
    class ios extends ios_base
    class basic_streambuf #aliceblue;line:blue;line.dotted;text:blue
}
ios_base *- "2" iostate : include >
ios_base *- "1" fmtflags #line:red;line.bold;text:red : >
class basic_istream extends basic_ios
class basic_ostream extends basic_ios

class basic_ifstream extends basic_istream
class basic_istringstream extends basic_istream
class basic_ofstream extends basic_ostream
class basic_ostringstream extends basic_ostream
class basic_iostream extends basic_istream,basic_ostream

class basic_fstream extends basic_iostream
class basic_stringstream extends basic_iostream
class basic_filebuf extends basic_streambuf
class basic_stringbuf extends basic_streambuf

package ostream {
    class ostream extends ios
}
package istream {
    class istream extends ios
    class iostream extends istream,ostream
}
package streambuf {
    class streambuf
}
package fstream {
    class ifstream extends istream
    class ofstream extends ostream
    class fstream extends iostream
    class filebuf extends streambuf
}
package sstream {
    class istringstream extends istream
    class ostringstream extends ostream
    class stringstream extends iostream
    class stringbuf extends streambuf
}
@enduml

