@startuml
'https://plantuml.com/sequence-diagram

'!$BGCOLOR="white"
'!theme materia
' or !include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia/puml-theme-materia.puml

skin rose
/'
<style>
    sequenceDiagram {
        participant {
            FontColor Black
            LineColor red
            BackGroundColor LightYellow
        }
    }
</style>

skinparam backGroundColor white
skinparam handwritten true
skinparam roundCorner 10
skinparam sequence {
    participantBorderThickness 2
    participantBorderColor red
    participantBackgroundColor business
    participantFontColor Black
    participantFontSize 17

    lifeLineBorderColor red
    lifeLineBackgroundColor white

    arrowColor red
}
'/

'autonumber start step "<b><color:red>0|#."
autonumber 1 1 "<b><color:blue>."
|||
group 测试 [继续]
    activate Alice #gold

    Alice -> Bob ++ : Authentication Request
    Alice <-- Bob -- : Authentication Response

    Alice -> Bob: Another authentication Request
    return another authentication Response
end
|||

@enduml